/* ============================================================
 * Space Defender 3D - Hand-crafted game logic
 * All OBJ models are generated by generate_models.py
 * ============================================================ */

(function () {
  'use strict';

  // ---------- 全局状态 ----------
  let scene, camera, renderer;
  let player, playerMaterial;
  let objects = {
    playerShip: null,
    enemyShip: null,
    bullet: null,
    star: null,
    asteroid: null,
  };

  const bullets = [];
  const enemies = [];
  const stars = [];
  const asteroids = [];
  const explosions = [];
  const stars_bg = []; // 背景星空粒子

  const keys = {};
  let mouseX = 0, mouseY = 0;
  let gameState = 'menu'; // menu | playing | paused | gameover
  let score = 0;
  let lives = 3;
  let level = 1;
  let shootCooldown = 0;
  let spawnTimer = 0;
  let starSpawnTimer = 0;
  let asteroidSpawnTimer = 0;

  const PLAYER_SPEED = 0.25;
  const BULLET_SPEED = 0.6;
  const ENEMY_SPEED = 0.08;
  const BOUNDS_X = 12;
  const BOUNDS_Y = 7;

  // ---------- DOM ----------
  const $ = (id) => document.getElementById(id);
  const hud = $('hud');
  const scoreEl = $('score');
  const livesEl = $('lives');
  const levelEl = $('level');

  // ============================================================
  // 初始化
  // ============================================================
  function init() {
    initThree();
    initLights();
    initBackground();
    bindEvents();
    loadModels().then(() => {
      createPlayer();
      animate();
    });
  }

  function initThree() {
    const canvas = $('game-canvas');
    scene = new THREE.Scene();
    scene.fog = new THREE.Fog(0x000010, 30, 120);

    camera = new THREE.PerspectiveCamera(
      70,
      window.innerWidth / window.innerHeight,
      0.1,
      200
    );
    camera.position.set(0, 0, -18);
    camera.lookAt(0, 0, 10);

    renderer = new THREE.WebGLRenderer({ canvas, antialias: true });
    renderer.setSize(window.innerWidth, window.innerHeight);
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  }

  function initLights() {
    const ambient = new THREE.AmbientLight(0x404060, 1.2);
    scene.add(ambient);

    const dir = new THREE.DirectionalLight(0xffffff, 1.0);
    dir.position.set(5, 10, 5);
    scene.add(dir);

    const p1 = new THREE.PointLight(0x00ffff, 1.5, 50);
    p1.position.set(-10, 5, -5);
    scene.add(p1);

    const p2 = new THREE.PointLight(0xff4466, 1.0, 50);
    p2.position.set(10, -5, -5);
    scene.add(p2);
  }

  // 背景星空
  function initBackground() {
    const geo = new THREE.BufferGeometry();
    const count = 800;
    const positions = new Float32Array(count * 3);
    for (let i = 0; i < count; i++) {
      positions[i * 3] = (Math.random() - 0.5) * 200;
      positions[i * 3 + 1] = (Math.random() - 0.5) * 200;
      positions[i * 3 + 2] = Math.random() * 150;
    }
    geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
    const mat = new THREE.PointsMaterial({
      color: 0xffffff,
      size: 0.3,
      transparent: true,
      opacity: 0.8,
    });
    const points = new THREE.Points(geo, mat);
    scene.add(points);
    stars_bg.push(points);
  }

  // ============================================================
  // 加载 OBJ 模型
  // ============================================================
  function loadModels() {
    return new Promise((resolve) => {
      const loader = new THREE.OBJLoader();
      const tasks = [
        ['playerShip', 'models/player_ship.obj', 0x00aaff],
        ['enemyShip', 'models/enemy_ship.obj', 0xff4466],
        ['bullet', 'models/bullet.obj', 0xffff00],
        ['star', 'models/star.obj', 0xffdd00],
        ['asteroid', 'models/asteroid.obj', 0x888888],
      ];
      let loaded = 0;
      tasks.forEach(([key, url, color]) => {
        loader.load(url, (obj) => {
          // 给所有 mesh 加统一材质
          obj.traverse((child) => {
            if (child.isMesh) {
              child.material = new THREE.MeshStandardMaterial({
                color: color,
                emissive: color,
                emissiveIntensity: 0.4,
                wireframe: false,
                metalness: 0.3,
                roughness: 0.5,
              });
            }
          });
          objects[key] = obj;
          loaded++;
          if (loaded === tasks.length) resolve();
        }, undefined, (err) => {
          console.error('Failed to load', url, err);
          loaded++;
          if (loaded === tasks.length) resolve();
        });
      });
    });
  }

  // ============================================================
  // 玩家
  // ============================================================
  function createPlayer() {
    player = objects.playerShip.clone();
    player.scale.set(1.2, 1.2, 1.2);
    player.position.set(0, 0, -10);
    scene.add(player);
  }

  // ============================================================
  // 生成敌人 / 星星 / 陨石
  // ============================================================
  function spawnEnemy() {
    const e = objects.enemyShip.clone();
    e.scale.set(1.0 + Math.random() * 0.5, 1.0 + Math.random() * 0.5, 1.0);
    e.position.set(
      (Math.random() - 0.5) * 30,
      (Math.random() - 0.5) * 14,
      60 + Math.random() * 20
    );
    e.rotation.y = Math.PI; // 面向玩家
    scene.add(e);
    enemies.push({
      mesh: e,
      speed: ENEMY_SPEED + level * 0.02 + Math.random() * 0.05,
      drift: (Math.random() - 0.5) * 0.02,
    });
  }

  function spawnStar() {
    const s = objects.star.clone();
    s.scale.set(0.8, 0.8, 0.8);
    s.position.set(
      (Math.random() - 0.5) * 25,
      (Math.random() - 0.5) * 12,
      50 + Math.random() * 15
    );
    scene.add(s);
    stars.push({ mesh: s, speed: 0.15 });
  }

  function spawnAsteroid() {
    const a = objects.asteroid.clone();
    const s = 0.8 + Math.random() * 1.5;
    a.scale.set(s, s, s);
    a.position.set(
      (Math.random() - 0.5) * 40,
      (Math.random() - 0.5) * 18,
      70 + Math.random() * 20
    );
    a.rotation.set(Math.random() * Math.PI, Math.random() * Math.PI, 0);
    scene.add(a);
    asteroids.push({
      mesh: a,
      speed: 0.05 + Math.random() * 0.1,
      rotX: (Math.random() - 0.5) * 0.02,
      rotY: (Math.random() - 0.5) * 0.02,
    });
  }

  // ============================================================
  // 射击
  // ============================================================
  function shoot() {
    if (shootCooldown > 0) return;
    shootCooldown = 10; // 帧冷却

    const b = objects.bullet.clone();
    b.scale.set(0.5, 0.5, 0.5);
    b.position.copy(player.position);
    b.position.z += 1.5;
    scene.add(b);
    bullets.push({ mesh: b, speed: BULLET_SPEED });
  }

  // ============================================================
  // 爆炸粒子效果
  // ============================================================
  function spawnExplosion(position, color) {
    const count = 20;
    const geo = new THREE.BufferGeometry();
    const positions = new Float32Array(count * 3);
    const velocities = [];
    for (let i = 0; i < count; i++) {
      positions[i * 3] = position.x;
      positions[i * 3 + 1] = position.y;
      positions[i * 3 + 2] = position.z;
      velocities.push(
        new THREE.Vector3(
          (Math.random() - 0.5) * 0.5,
          (Math.random() - 0.5) * 0.5,
          (Math.random() - 0.5) * 0.5
        )
      );
    }
    geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
    const mat = new THREE.PointsMaterial({
      color: color || 0xffaa00,
      size: 0.3,
      transparent: true,
      opacity: 1,
    });
    const points = new THREE.Points(geo, mat);
    scene.add(points);
    explosions.push({ points, velocities, life: 30 });
  }

  // ============================================================
  // 碰撞检测（简易球形距离）
  // ============================================================
  function dist2D(a, b) {
    const dx = a.x - b.x;
    const dy = a.y - b.y;
    const dz = a.z - b.z;
    return Math.sqrt(dx * dx + dy * dy + dz * dz);
  }

  // ============================================================
  // 游戏更新
  // ============================================================
  function update() {
    if (gameState !== 'playing') return;

    // --- 玩家移动 ---
    if (keys['KeyW'] || keys['ArrowUp']) player.position.y += PLAYER_SPEED;
    if (keys['KeyS'] || keys['ArrowDown']) player.position.y -= PLAYER_SPEED;
    if (keys['KeyA'] || keys['ArrowLeft']) player.position.x -= PLAYER_SPEED;
    if (keys['KeyD'] || keys['ArrowRight']) player.position.x += PLAYER_SPEED;

    // 鼠标瞄准偏移
    player.position.x += mouseX * 0.1;
    player.position.y += mouseY * 0.1;
    mouseX *= 0.9;
    mouseY *= 0.9;

    // 边界
    player.position.x = Math.max(-BOUNDS_X, Math.min(BOUNDS_X, player.position.x));
    player.position.y = Math.max(-BOUNDS_Y, Math.min(BOUNDS_Y, player.position.y));

    // 飞船倾斜效果
    player.rotation.z = -player.position.x * 0.03;
    player.rotation.x = player.position.y * 0.03;

    // --- 射击冷却 ---
    if (shootCooldown > 0) shootCooldown--;
    if (keys['Space']) shoot();

    // --- 生成敌人 ---
    spawnTimer--;
    if (spawnTimer <= 0) {
      spawnEnemy();
      spawnTimer = Math.max(30, 90 - level * 8);
    }

    starSpawnTimer--;
    if (starSpawnTimer <= 0) {
      spawnStar();
      starSpawnTimer = 200 + Math.random() * 150;
    }

    asteroidSpawnTimer--;
    if (asteroidSpawnTimer <= 0) {
      spawnAsteroid();
      asteroidSpawnTimer = 120 + Math.random() * 100;
    }

    // --- 子弹移动 ---
    for (let i = bullets.length - 1; i >= 0; i--) {
      const b = bullets[i];
      b.mesh.position.z += b.speed;
      if (b.mesh.position.z > 80) {
        scene.remove(b.mesh);
        bullets.splice(i, 1);
      }
    }

    // --- 敌人移动 ---
    for (let i = enemies.length - 1; i >= 0; i--) {
      const e = enemies[i];
      e.mesh.position.z -= e.speed;
      e.mesh.position.x += e.drift;
      e.mesh.rotation.z += 0.02;

      if (e.mesh.position.z < player.position.z - 5) {
        // 敌人飞出屏幕底部，扣血
        scene.remove(e.mesh);
        enemies.splice(i, 1);
        damagePlayer();
        continue;
      }

      // 子弹 vs 敌人
      for (let j = bullets.length - 1; j >= 0; j--) {
        const b = bullets[j];
        if (dist2D(b.mesh.position, e.mesh.position) < 1.5) {
          scene.remove(b.mesh);
          bullets.splice(j, 1);
          scene.remove(e.mesh);
          enemies.splice(i, 1);
          spawnExplosion(e.mesh.position, 0xff4466);
          score += 100;
          updateHUD();
          break;
        }
      }

      // 玩家 vs 敌人
      if (dist2D(player.position, e.mesh.position) < 1.8) {
        scene.remove(e.mesh);
        enemies.splice(i, 1);
        spawnExplosion(player.position, 0xff0000);
        damagePlayer();
      }
    }

    // --- 星星移动 ---
    for (let i = stars.length - 1; i >= 0; i--) {
      const s = stars[i];
      s.mesh.position.z -= s.speed;
      s.mesh.rotation.y += 0.05;
      s.mesh.rotation.x += 0.02;

      if (s.mesh.position.z < -20) {
        scene.remove(s.mesh);
        stars.splice(i, 1);
        continue;
      }
      if (dist2D(player.position, s.mesh.position) < 2.0) {
        scene.remove(s.mesh);
        stars.splice(i, 1);
        spawnExplosion(s.mesh.position, 0xffdd00);
        score += 50;
        updateHUD();
      }
    }

    // --- 陨石移动 ---
    for (let i = asteroids.length - 1; i >= 0; i--) {
      const a = asteroids[i];
      a.mesh.position.z -= a.speed;
      a.mesh.rotation.x += a.rotX;
      a.mesh.rotation.y += a.rotY;

      if (a.mesh.position.z < -20) {
        scene.remove(a.mesh);
        asteroids.splice(i, 1);
        continue;
      }
      // 玩家 vs 陨石
      if (dist2D(player.position, a.mesh.position) < 1.5) {
        scene.remove(a.mesh);
        asteroids.splice(i, 1);
        spawnExplosion(a.mesh.position, 0x888888);
        damagePlayer();
      }
      // 子弹 vs 陨石
      for (let j = bullets.length - 1; j >= 0; j--) {
        const b = bullets[j];
        if (dist2D(b.mesh.position, a.mesh.position) < 1.2) {
          scene.remove(b.mesh);
          bullets.splice(j, 1);
          break; // 子弹被吸收
        }
      }
    }

    // --- 爆炸粒子 ---
    for (let i = explosions.length - 1; i >= 0; i--) {
      const ex = explosions[i];
      ex.life--;
      const pos = ex.points.geometry.attributes.position.array;
      for (let k = 0; k < ex.velocities.length; k++) {
        pos[k * 3] += ex.velocities[k].x;
        pos[k * 3 + 1] += ex.velocities[k].y;
        pos[k * 3 + 2] += ex.velocities[k].z;
      }
      ex.points.geometry.attributes.position.needsUpdate = true;
      ex.points.material.opacity = ex.life / 30;
      if (ex.life <= 0) {
        scene.remove(ex.points);
        explosions.splice(i, 1);
      }
    }

    // --- 背景星空滚动 ---
    stars_bg.forEach((s) => {
      const pos = s.geometry.attributes.position.array;
      for (let k = 0; k < pos.length; k += 3) {
        pos[k + 2] -= 0.3;
        if (pos[k + 2] < -50) pos[k + 2] = 150;
      }
      s.geometry.attributes.position.needsUpdate = true;
    });

    // --- 升级 ---
    const newLevel = Math.floor(score / 500) + 1;
    if (newLevel > level) {
      level = newLevel;
      updateHUD();
    }
  }

  function damagePlayer() {
    lives--;
    updateHUD();
    if (lives <= 0) {
      gameOver();
    }
  }

  function updateHUD() {
    scoreEl.textContent = score;
    livesEl.textContent = '♥'.repeat(Math.max(0, lives)) || '—';
    levelEl.textContent = level;
  }

  // ============================================================
  // 游戏流程
  // ============================================================
  function startGame() {
    // 清理
    [...bullets, ...enemies, ...stars, ...asteroids].forEach((o) =>
      scene.remove(o.mesh)
    );
    bullets.length = 0;
    enemies.length = 0;
    stars.length = 0;
    asteroids.length = 0;

    score = 0;
    lives = 3;
    level = 1;
    shootCooldown = 0;
    spawnTimer = 30;
    starSpawnTimer = 150;
    asteroidSpawnTimer = 100;

    player.position.set(0, 0, -10);
    updateHUD();

    gameState = 'playing';
    $('start-screen').classList.add('hidden');
    $('gameover-screen').classList.add('hidden');
    $('pause-screen').classList.add('hidden');
    hud.classList.remove('hidden');
  }

  function gameOver() {
    gameState = 'gameover';
    $('final-score').textContent = score;
    $('final-level').textContent = level;
    $('gameover-screen').classList.remove('hidden');
    hud.classList.add('hidden');
  }

  function togglePause() {
    if (gameState === 'playing') {
      gameState = 'paused';
      $('pause-screen').classList.remove('hidden');
    } else if (gameState === 'paused') {
      gameState = 'playing';
      $('pause-screen').classList.add('hidden');
    }
  }

  // ============================================================
  // 事件绑定
  // ============================================================
  function bindEvents() {
    window.addEventListener('resize', () => {
      camera.aspect = window.innerWidth / window.innerHeight;
      camera.updateProjectionMatrix();
      renderer.setSize(window.innerWidth, window.innerHeight);
    });

    window.addEventListener('keydown', (e) => {
      keys[e.code] = true;
      if (e.code === 'KeyP') togglePause();
      if (e.code === 'Space') e.preventDefault();
    });
    window.addEventListener('keyup', (e) => {
      keys[e.code] = false;
    });

    // 鼠标移动 -> 瞄准
    window.addEventListener('mousemove', (e) => {
      mouseX = (e.clientX / window.innerWidth - 0.5) * 2;
      mouseY = -(e.clientY / window.innerHeight - 0.5) * 2;
    });

    // 触屏支持
    window.addEventListener('touchmove', (e) => {
      if (e.touches.length > 0) {
        const t = e.touches[0];
        mouseX = (t.clientX / window.innerWidth - 0.5) * 2;
        mouseY = -(t.clientY / window.innerHeight - 0.5) * 2;
      }
    });
    window.addEventListener('touchstart', (e) => {
      if (gameState === 'playing') keys['Space'] = true;
    });
    window.addEventListener('touchend', () => {
      keys['Space'] = false;
    });

    $('start-btn').addEventListener('click', startGame);
    $('restart-btn').addEventListener('click', startGame);
  }

  // ============================================================
  // 主循环
  // ============================================================
  function animate() {
    requestAnimationFrame(animate);
    update();
    renderer.render(scene, camera);
  }

  // 启动
  window.addEventListener('load', init);
})();
