#!/usr/bin/env python3
"""
Space Defender 3D - OBJ Model Generator
All models are hand-crafted as low-poly wireframe-style geometry.
Run: python3 generate_models.py
Outputs: models/*.obj
"""
import math
import os

MODELS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "models")
os.makedirs(MODELS_DIR, exist_ok=True)


def write_obj(filename, vertices, faces):
    """Write a Wavefront OBJ file."""
    path = os.path.join(MODELS_DIR, filename)
    with open(path, "w") as f:
        f.write(f"# {filename} - generated by hand\n")
        f.write(f"# Vertices: {len(vertices)}, Faces: {len(faces)}\n")
        for v in vertices:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
        for face in faces:
            # OBJ indices are 1-based
            idx = " ".join(str(i + 1) for i in face)
            f.write(f"f {idx}\n")
    print(f"  -> {path}  ({len(vertices)} verts, {len(faces)} faces)")


# ---------------------------------------------------------------------------
# 1. Player Ship - arrowhead / dart shape with swept wings
# ---------------------------------------------------------------------------
def gen_player_ship():
    verts = []
    faces = []

    # Nose tip
    nose = (0, 0, 3.0)
    verts.append(nose)

    # Cockpit ring (mid)
    cockpit = [
        (0, 0.4, 0.5),
        (0.5, 0, 0.5),
        (0, -0.4, 0.5),
        (-0.5, 0, 0.5),
    ]
    verts.extend(cockpit)

    # Wing tips (rear)
    wings = [
        (1.8, 0, -1.5),
        (-1.8, 0, -1.5),
        (0, 0.2, -1.0),   # tail top
        (0, -0.2, -1.0),  # tail bottom
    ]
    verts.extend(wings)

    # Indices: 0=nose, 1..4=cockpit ring, 5..8=wings/tail
    # Nose to cockpit cone
    for i in range(4):
        faces.append((0, 1 + i, 1 + ((i + 1) % 4)))

    # Cockpit to fuselage ring
    for i in range(4):
        a = 1 + i
        b = 1 + ((i + 1) % 4)
        if i == 0:   # top
            faces.append((a, 6, b))  # cockpit top -> tail top
        elif i == 1: # right
            faces.append((a, 5, b))  # cockpit right -> wing right
        elif i == 2: # bottom
            faces.append((a, 7, b))  # cockpit bottom -> tail bottom
        else:        # left
            faces.append((a, 6, b))  # hmm, need care
    # Let's redo cleanly with explicit faces below

    # Clean face list
    faces = []
    # Nose cone
    faces.append((0, 1, 2))
    faces.append((0, 2, 3))
    faces.append((0, 3, 4))
    faces.append((0, 4, 1))
    # Right wing: cockpit right (2) -> right wing tip (5) -> cockpit bottom (3)
    faces.append((2, 5, 3))
    # Left wing: cockpit left (4) -> left wing tip (6) -> cockpit top (1)
    faces.append((4, 6, 1))
    # Hmm wait indices: 5=right wing, 6=left wing, 7=tail top, 8=tail bottom
    # Let me re-map:
    # 0: nose
    # 1: cockpit top
    # 2: cockpit right
    # 3: cockpit bottom
    # 4: cockpit left
    # 5: right wing tip
    # 6: left wing tip
    # 7: tail top
    # 8: tail bottom

    faces = []
    # Nose cone
    faces.append((0, 1, 2))
    faces.append((0, 2, 3))
    faces.append((0, 3, 4))
    faces.append((0, 4, 1))
    # Right wing surface
    faces.append((2, 5, 3))
    faces.append((3, 5, 8))   # right wing down to tail bottom
    # Left wing surface
    faces.append((4, 6, 1))
    faces.append((1, 6, 7))   # left wing up to tail top
    # Tail bottom
    faces.append((3, 8, 7))
    faces.append((3, 7, 1))
    # Tail rear triangle (close the back)
    faces.append((5, 8, 6))
    faces.append((6, 8, 7))
    faces.append((7, 8, 5))
    faces.append((7, 5, 6))

    write_obj("player_ship.obj", verts, faces)


# ---------------------------------------------------------------------------
# 2. Enemy Ship - flattened diamond / kite shape
# ---------------------------------------------------------------------------
def gen_enemy_ship():
    verts = []
    faces = []

    # Center top
    top = (0, 1.2, 0)
    verts.append(top)
    # Center bottom
    bottom = (0, -0.3, 0)
    verts.append(bottom)

    # Four corner points (flat diamond, pointing forward = +Z)
    corners = [
        (0, 0, 2.0),    # 2: front tip
        (1.5, 0, -0.8), # 3: right
        (0, 0, -1.5),   # 4: back
        (-1.5, 0, -0.8),# 5: left
    ]
    verts.extend(corners)

    # 0=top, 1=bottom, 2=front, 3=right, 4=back, 5=left
    faces = [
        # Top pyramid
        (0, 2, 3),
        (0, 3, 4),
        (0, 4, 5),
        (0, 5, 2),
        # Bottom pyramid
        (1, 3, 2),
        (1, 4, 3),
        (1, 5, 4),
        (1, 2, 5),
    ]
    write_obj("enemy_ship.obj", verts, faces)


# ---------------------------------------------------------------------------
# 3. Bullet - elongated octahedron (a spiky capsule)
# ---------------------------------------------------------------------------
def gen_bullet():
    verts = []
    faces = []

    # Top and bottom tips
    verts.append((0, 0, 1.0))    # 0: top
    verts.append((0, 0, -1.0))   # 1: bottom

    # Middle ring (4 points)
    ring = [
        (0.15, 0, 0),
        (0, 0.15, 0),
        (-0.15, 0, 0),
        (0, -0.15, 0),
    ]
    verts.extend(ring)
    # 0=top, 1=bottom, 2..5=ring

    faces = [
        (0, 2, 3), (0, 3, 4), (0, 4, 5), (0, 5, 2),
        (1, 3, 2), (1, 4, 3), (1, 5, 4), (1, 2, 5),
    ]
    write_obj("bullet.obj", verts, faces)


# ---------------------------------------------------------------------------
# 4. Star / Power-up - 3D extruded star
# ---------------------------------------------------------------------------
def gen_star():
    verts = []
    faces = []

    outer_r = 1.0
    inner_r = 0.45
    thickness = 0.25
    points = 5

    # Front face (z = +thickness/2)
    for i in range(points * 2):
        angle = math.pi / 2 + i * math.pi / points
        r = outer_r if i % 2 == 0 else inner_r
        x = r * math.cos(angle)
        y = r * math.sin(angle)
        verts.append((x, y, thickness / 2))

    # Back face (z = -thickness/2)
    for i in range(points * 2):
        angle = math.pi / 2 + i * math.pi / points
        r = outer_r if i % 2 == 0 else inner_r
        x = r * math.cos(angle)
        y = r * math.sin(angle)
        verts.append((x, y, -thickness / 2))

    n = points * 2  # 10 vertices per face

    # Front face (fan)
    for i in range(1, n - 1):
        faces.append((0, i, i + 1))
    # Back face (reversed winding)
    for i in range(1, n - 1):
        faces.append((n, n + i + 1, n + i))
    # Side walls
    for i in range(n):
        a = i
        b = (i + 1) % n
        faces.append((a, b, n + b))
        faces.append((a, n + b, n + a))

    write_obj("star.obj", verts, faces)


# ---------------------------------------------------------------------------
# 5. Asteroid - rough icosahedron-ish rock
# ---------------------------------------------------------------------------
def gen_asteroid():
    verts = []
    faces = []

    # Icosahedron base
    t = (1.0 + math.sqrt(5.0)) / 2.0
    raw = [
        (-1, t, 0), (1, t, 0), (-1, -t, 0), (1, -t, 0),
        (0, -1, t), (0, 1, t), (0, -1, -t), (0, 1, -t),
        (t, 0, -1), (t, 0, 1), (-t, 0, -1), (-t, 0, 1),
    ]
    # Normalize and add slight random jitter for rocky look
    import random
    random.seed(42)
    for v in raw:
        length = math.sqrt(sum(c * c for c in v))
        scale = 0.6 / length * random.uniform(0.8, 1.2)
        verts.append((v[0] * scale, v[1] * scale, v[2] * scale))

    faces = [
        (0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
        (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
        (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
        (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1),
    ]
    write_obj("asteroid.obj", verts, faces)


if __name__ == "__main__":
    print("Generating OBJ models...")
    gen_player_ship()
    gen_enemy_ship()
    gen_bullet()
    gen_star()
    gen_asteroid()
    print("Done!")
